---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: epuakyiw1478t1:32177/helm-flux:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:MyroslavSeliverstov/helm-operator-get-started.git
    path: charts/podinfo
    ref: master
  values:
    image: epuakyiw1478t1:32177/helm-flux:dev-yi4ok62l
    replicaCount: 1
    hpa:
      enabled: false
