apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
  - image: myroslavseliverstov/porter
    context: porter
#    kaniko:
    docker:
#      buildContext:
#          localDir: {}
#      cache:
#        repo: myroslavseliverstov/porter-cache
      buildArgs:
        BUNDLE_DIR: /cnab/app
#  cluster:
#    namespace: default
#    dockerConfig:
#      secretName: dockerdc
deploy:
  helm:
    releases:
    - name: porter-helm
      chartPath: charts/porter
      namespace: default
      values:
        image: myroslavseliverstov/porter
      setValues:
        imagePullSecrets[0].name: docker

#profiles:
#  - name: dev
#    patches:
#      - op: replace
#        path: /build/tagPolicy
#        value: { envTemplate:  { template: "{{ .IMAGE_NAME }}:dev-{{ AbbrevCommitSha }}" } }
#  - name: prod
#    patches:
#      - op: replace
#        path: /build/tagPolicy
#        value: { envTemplate:  { template: "{{ .IMAGE_NAME }}:dev-{{ randNumeric 5 }}" } }
