---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: porter-test
  namespace: porter
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: porter
  chart:
    git: git@github.com:MyroslavSeliverstov/helm-operator-get-started.git
    path: charts/porter
    ref: master
  values:
    image: myroslavseliverstov/porter:dev-7be81c43
    imagePullSecrets:
    - name: docker
    namespace: porter
