---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: porter-dev
  namespace: porter-dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: porter
  chart:
    git: git@github.com:MyroslavSeliverstov/helm-operator-get-started.git
    path: charts/porter
    ref: master
  values:
    image: quay.io/myroslavseliverstov/porter:dev-qackfhgg
    imagePullSecrets:
    - name: quay
    namespace: porter
