---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: porter-prod
  namespace: porter-prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.1
spec:
  releaseName: porter
  chart:
    git: git@github.com:MyroslavSeliverstov/helm-operator-get-started.git
    path: charts/porter
    ref: master
  values:
    image: quay.io/myroslavseliverstov/porter:0.1.8
    imagePullSecrets:
    - name: quay
    namespace: porter
